### ISSUE TITLE
能写一个详细点儿的说明吗？

### ISSUE THREAD

**Issue by flypigxyz** [joelYing/XimalayaFM#1]
不清楚如何使用啊。

**Comment by JiangLennon** [comment]
搭建python3环境，把_vip的py文件丢到vs_code里运行，缺什么包pip3 install。
下载winpcap，google的驱动，运行后能看到界面基本就OK了，不行的话再看看terminal里报什么错。

**Comment by BetterSci** [comment]
348 这行命令总是出错

**Comment by BetterSci** [comment]
Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

**Comment by JiangLennon** [comment]
> 
> 
> Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

先声明一下，作者莫怪。

我用下来通过winpcap可靠性和速度一般，你可以找找用node.js的方案，thread-1112519-1-1.html

**Comment by joelYing** [comment]
> > Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
> 
> 先声明一下，作者莫怪。
> 
> 我用下来通过winpcap可靠性和速度一般，你可以找找用node.js的方案，thread-1112519-1-1.html

没事哈哈，这个问题我刚刚测试了下好像是嗅探的数据包中的没有HTTP段的内容，所以vip音频目前应该是下载不了了

**Comment by JiangLennon** [comment]
> 
> 
> > > Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
> > 
> > 
> > 先声明一下，作者莫怪。
> > 我用下来通过winpcap可靠性和速度一般，你可以找找用node.js的方案，thread-1112519-1-1.html
> 
> 没事哈哈，这个问题我刚刚测试了下好像是嗅探的数据包中的没有HTTP段的内容，所以vip音频目前应该是下载不了了

能下，之前下了好多，谢谢作者。
其实本来也就用下去了，忽然发现有几次文件下不全，所以提了个下单个文件的要求。
然后，到52pojie看到有基于node的方案，更直接。

**Comment by joelYing** [comment]
> > > > Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
> > > 
> > > 
> > > 先声明一下，作者莫怪。
> > > 我用下来通过winpcap可靠性和速度一般，你可以找找用node.js的方案，thread-1112519-1-1.html
> > 
> > 
> > 没事哈哈，这个问题我刚刚测试了下好像是嗅探的数据包中的没有HTTP段的内容，所以vip音频目前应该是下载不了了
> 
> 能下，之前下了好多，谢谢作者。
> 其实本来也就用下去了，忽然发现有几次文件下不全，所以提了个下单个文件的要求。
> 然后，到52pojie看到有基于node的方案，更直接。

天呐还能下......我去找找我的问题，52的大神多啊，溜了溜了~

**Comment by BetterSci** [comment]
谢谢你node.js方案的链接吗？我想自己摸索下，python初学者

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: joelYing <notifications@github.com>
发送时间: Saturday, March 7, 2020 12:59:20 PM
收件人: joelYing/XimalayaFM <XimalayaFM@noreply.github.com>
抄送: BetterSci <zhouweihua2@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [joelYing/XimalayaFM] 能写一个详细点儿的说明吗？ (#1)


Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

先声明一下，作者莫怪。
我用下来通过winpcap可靠性和速度一般，你可以找找用node.js的方案，thread-1112519-1-1.html

没事哈哈，这个问题我刚刚测试了下好像是嗅探的数据包中的没有HTTP段的内容，所以vip音频目前应该是下载不了了

能下，之前下了好多，谢谢作者。
其实本来也就用下去了，忽然发现有几次文件下不全，所以提了个下单个文件的要求。
然后，到52pojie看到有基于node的方案，更直接。

天呐还能下......我去找找我的问题，52的大神多啊，溜了溜了~

―

**Comment by JiangLennon** [comment]
上面都写了啊，拼起来就是：https://www.52pojie.cn/thread-1112519-1-1.html
