### ISSUE TITLE
你好，能不能写一个模拟VIP账号登录 下载VIP付费专辑脚本

### ISSUE THREAD

**Issue by yonggedebaqi** [joelYing/XimalayaFM#2]
你好，能不能写一个模拟 喜马拉雅FMVIP账号登录 下载VIP付费专辑脚本

**Comment by skygongque** [comment]
今天试了一下pc端的模拟登录，搞定了V1接口的password(rsa加密后base64编码)，nonce(get请求得到)，signature(account，加密后密码，nonce等字符串的sha1)
但发现在这个请求前还有一个slide接口的post滑块验证，
滑块验证通过后并没有set-cookie，未知如何识别用户，猜测是中间还有一个对V1的post的作用，实在是搞不动了

**Comment by BetterSci** [comment]
This content should also be served over HTTPS，py代码348行报错

**Comment by BetterSci** [comment]
报错：
Mixed Content: The page at 
 This content should also be served over HTTPS
