### ISSUE TITLE
超赞的xmly下载器，2个建议

### ISSUE THREAD

**Issue by JiangLennon** [joelYing/XimalayaFM#4]
1，Line288，path + title之间，可能要加一个\，否则下载的文件没归到目录下：path + '\\' + title
2，网络不稳定的情况下，可能会有几个文件下载不完整，能不能增加一个TrackID输入，在单个音频选项选中的情况下，只下载音频ID+TrackID对应的文件。

多谢提供如此优秀的下载器！

**Comment by joelYing** [comment]
1、谢谢你的建议，之前测试的时候一直用的是固定路径，所以重新上传时没注意到这一点，已经修改啦；同时也修改了vip下载的api，换成了另一个，因为之前一个的pageSize有限制，最大1000，所以对于原来的逻辑有影响，导致我下载《圣墟》这种大章节的有声书会出问题
2、关于第二点我觉得你完全有能力可以自己增加哈哈，当然我也会，嗯......在不久的将来？找时间重新写一下
